#!/usr/bin/env bash

if [ -n "$1" ] && [ "$1" == "compile" ]; then

    ADDONS=""
    if [ -e addons.js ]; then
        ADDONS=" -i ./addons.js "
    fi

    jam compile -i js/main $ADDONS  -o jam/require.prod.js;
else
    if [ -e "jam/require.prod.js" ]; then
        rm jam/require.prod.js;
    fi
fi